### ISSUE TITLE
[Feature] Add Notes on Depth-First Search (DFS)

### ISSUE THREAD

**Issue by visheshrwl** [visheshrwl/DSA-Notes#4]
Hacktoberfest Label: Yes

### Description
DFS is a crucial graph traversal algorithm, and high-quality notes would benefit both beginners and experienced programmers.

### Scope: 

> This feature request involves adding comprehensive notes about Depth-First Search (DFS).

### Suggested Implementation:

> Create a new directory named "Depth-First Search (DFS)."
> Inside the directory, add detailed notes in Markdown format.
> Include explanations, examples, and pseudocode.
> Ensure clarity and thorough coverage of DFS.

### Contribution Guidelines:

> Please adhere to the repository's contribution guidelines, including coding style, licensing, and formatting instructions.
> Ensure your contributions are original or properly attributed to sources.

### Expected Outcome:

> By the end of Hacktoberfest, the repository should have valuable notes on Depth-First Search (DFS).

### Additional Information:

> Feel free to contact us if you have questions or need assistance while contributing.

**Hacktoberfest: This issue is tagged for Hacktoberfest.**

**Comment by fawadta** [comment]
assign me this

**Comment by fawadta** [comment]
@visheshrwl close this issue too 😊

**Comment by visheshrwl** [comment]
@fawadta Star the repo for better Reach and also try to create issues.

**Comment by fawadta** [comment]
> @fawadta Star the repo for better Reach and also try to create issues.

alright. i'll try
